name: Linux

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version:
          - '3.7'
          #- '3.9'
          #- '3.10'
          
    steps:
  
      - name: Set Git Describe Tag
        run: echo "GIT_DESCRIBE_TAG=(v1.0.0)" >> $GITHUB_ENV
        
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: List Repository Contents
        run: ls -R
        
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: n88
          auto-activate-base: true
          
      - run: |
          conda info
          conda list
          
      - name: Install conda-build
        run: conda install -c conda-forge conda-build

      - name: Set up Conda and Build
        run: |
          conda build conda-recipe/vtkbone -c Numerics88 -c conda-forge --python=${{ matrix.python_version }}
          
      - name: Copy conda build
        run: |
          mkdir -p $HOME/conda-bld/linux-64/
          cp /usr/share/miniconda/envs/n88/conda-bld/linux-64/*.tar.bz2 $HOME/conda-bld/linux-64/

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: vtkbone-Linux-${{ matrix.python_version }}
          path: $HOME/conda-bld/
