name: Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Set up Conda
        run: |
          python -m pip install conda
          conda create -y -n n88 conda-build
          source activate n88
          conda-build -c Numerics88 -c conda-forge conda-recipe/vtkbone/ --variants "{'python': ['${{ matrix.python_version }}']}"

      - name: Copy conda build
        run: |
          mkdir -p $HOME/conda-bld/linux-64/
          cp /usr/share/miniconda/envs/n88/conda-bld/linux-64/*.tar.bz2 $HOME/conda-bld/linux-64/

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: vtkbone-Linux-${{ matrix.python_version }}
          path: $HOME/conda-bld/linux-64/
