name: Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version:
          - '3.8'
          #- '3.9'
          #- '3.10'
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: List Repository Contents
        run: ls -R
        
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: n88
  
      - name: Install conda-build
        run: conda install -n n88 -c conda-forge conda-build

      - name: Set up Conda and Build
        run: |
          conda-build -c Numerics88 -c conda-forge conda-recipe/vtkbone/ --python=${{ matrix.python_version }} 

      - name: Copy conda build
        run: |
          mkdir -p $HOME/conda-bld/linux-64/
          cp /usr/share/miniconda/envs/n88/conda-bld/linux-64/*.tar.bz2 $HOME/conda-bld/linux-64/

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: vtkbone-Linux-${{ matrix.python_version }}
          path: $HOME/conda-bld/
